In [65]:
import tensorflow as tf
from tensorflow import keras


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?'
]

# tokenizer = Tokenizer(num_words = 100)
# tokenizer.fit_on_texts(sentences)
# word_index = tokenizer.word_index
# print("word_index ", word_index)


# Word not in the tokenizer
tokenizer = Tokenizer(num_words = 100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print("word_index", word_index)

sequences = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequences, maxlen=10)
print("\nWord Index = " , word_index)
print("\nSequences = " , sequences)
print("\nPadded Sequences:")
print(padded)





word_index {'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}

Word Index =  {'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}

Sequences =  [[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]

Padded Sequences:
[[ 0  0  0  0  0  0  5  3  2  4]
 [ 0  0  0  0  0  0  5  3  2  7]
 [ 0  0  0  0  0  0  6  3  2  4]
 [ 0  0  0  8  6  9  2  4 10 11]]


In [66]:
# Try with words that the tokenizer wasn't fit to
test_data = [
    'i really love my dog',
    'my dog loves my manatee'
]

test_seq = tokenizer.texts_to_sequences(test_data)
print("\nTest Sequence = ", test_seq)

padded = pad_sequences(test_seq)
print("\nPadded Test Sequence: ")
print(padded)




Test Sequence =  [[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]

Padded Test Sequence: 
[[5 1 3 2 4]
 [2 4 1 2 1]]


In [67]:
# !wget --no-check-certificate \
#     https://storage.googleapis.com/learning-datasets/sarcasm.json \
#     -O /media/nsl47/hdd/AI_project/AI/NLP_Projects_with_BOOBRA/week1/dataset/sarcasm.json

In [68]:
import json

with open("dataset/sarcasm.json", "r") as f:
    datastore = json.load(f)


sentences = []
labels = []
urls =[]


for item in datastore:
    sentences.append(item['headline'])
    labels.append(item['is_sarcastic'])
    urls.append(item['article_link'])



In [69]:
print(len(sentences))
print(type(sentences))

26709
<class 'list'>


In [70]:
vocab_size = 10000
embedding_dim = 16
max_length = 100
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"
training_size = 20000


In [71]:
training_sentences = sentences[0:training_size]
testing_sentences = sentences[training_size:]

training_labels = labels[0:training_size]
testing_labels = labels[training_size:]



In [72]:

tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index
# print("Word Index = ", word_index)

training_sequences = tokenizer.texts_to_sequences(training_sentences)
print("Training Sequences = ", training_sequences)    
training_padded = pad_sequences(training_sequences, max_length,padding=padding_type,truncating=trunc_type)
print("training padded = ", training_padded)

testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
print("Testing_sequences",testing_sentences)
testing_padded = pad_sequences(testing_sequences, max_length, padding=padding_type, truncating=trunc_type)
print("Testing padded", testing_padded)

Training Sequences =  [[328, 1, 799, 3405, 2404, 47, 389, 2214, 1, 6, 2614, 8863], [4, 6840, 3096, 3097, 23, 2, 161, 1, 390, 2842, 6, 251, 9, 889], [153, 890, 2, 891, 1445, 2215, 595, 5650, 221, 133, 36, 45, 2, 8864], [1252, 38, 213, 382, 2, 1572, 29, 288, 23, 10, 2405, 1446, 5651, 958], [715, 672, 5652, 1043, 8865, 662, 553, 5, 4, 92, 1253, 90], [8866, 4, 366, 70], [4, 6841, 369, 6, 498, 3406, 1875, 1378], [20, 563, 36, 1091, 31, 163, 2, 103, 87, 18, 150, 6, 33, 343], [278, 3407, 6842, 447, 8867, 2092, 148], [2093, 300, 335, 370, 63, 1, 6, 4, 4264], [3098, 2216, 3756, 14, 37, 5653, 8868, 5, 2094, 1092], [309, 767, 428, 8, 1663, 1664, 9, 3099], [226, 477, 2843, 13, 9, 922, 239, 371, 2, 4265, 1, 6843], [235, 5654, 8869, 3757, 39, 240, 1, 6, 7, 174], [1, 1379, 800, 663, 5, 336, 3, 959], [524, 2094, 8870, 126, 8871, 6, 8872, 3758, 1665], [2095, 1328, 341, 46, 3408, 323, 288, 960, 2, 22, 1, 19, 1044, 359, 109, 1447], [1666, 6844, 3100, 8873, 19, 5655, 1200], [8874, 822, 2, 1768, 251, 1201,

In [73]:
import numpy as np


training_padded = np.array(training_padded)
print('training_pad', training_padded)

training_labels = np.array(training_labels)
print('training_labels', training_labels)

testing_padded = np.array(testing_padded)
print('testing_pad', testing_padded)
testing_labels = np.array(testing_labels)
print('testing_labels  ', testing_labels)



training_pad [[ 328    1  799 ...    0    0    0]
 [   4 6840 3096 ...    0    0    0]
 [ 153  890    2 ...    0    0    0]
 ...
 [  79 1729    1 ...    0    0    0]
 [  53 5108 4735 ...    0    0    0]
 [ 312  705    1 ...    0    0    0]]
training_labels [0 0 1 ... 0 0 1]
testing_pad [[   1 1100 6663 ...    0    0    0]
 [ 202    1    8 ...    0    0    0]
 [  18  380  191 ...    0    0    0]
 ...
 [   1    9   67 ...    0    0    0]
 [1556  374 4114 ...    0    0    0]
 [   1 1700    6 ...    0    0    0]]
testing_labels   [1 0 0 ... 0 0 0]


In [74]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

2024-05-15 15:32:21.886360: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error


In [75]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ ?                      │   0 (unbuilt) │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
num_epochs = 30
history = model.fit(training_padded, training_labels, epochs=num_epochs, validation_data=(testing_padded, testing_labels), verbose=2)